In [1]:
import numpy as np

from machine_learning.ml_optimizer import timeit


# **Comparing process time**

#### first checking time of array then checking time of numpy


In [2]:
from time import process_time

import  numpy as np
a=[i for i in range(100000000)]
s_t=process_time()
a=[i+5 for i in a]
st_t=process_time()
print(st_t-s_t)

10.484375


In [3]:
import  numpy as np
np_array=np.array([i for i in range(100000000)])
s_t = process_time()
np_array+=5
st_t=process_time()
print(st_t-s_t)

0.171875


### **Huge time difference one is around 10 s another 0.17s**

# Initialize placeholder

In [7]:
x=np.zeros((2,2))

In [9]:
y=np.ones((2,2))

In [8]:
z=np.random.random((2,2))

In [11]:
w=np.random.randint((2,2))

In [13]:
print("X=",x)
print("Y=",y)
print("Z=",z)
print("w=",w)

X= [[0. 0.]
 [0. 0.]]
Y= [[1. 1.]
 [1. 1.]]
Z= [[0.01279058 0.4527378 ]
 [0.44384647 0.09486309]]
w= [0 1]


# **Mathmatics**

In [14]:
list1=[1,2,3,4]
list2=[5,6,7,8]
a=np.array(list1)
b=np.array(list2)
print("a=",a)
print("b=",b)

a= [1 2 3 4]
b= [5 6 7 8]


In [30]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [32]:
a.shape


(4,)

In [39]:
a = np.random.randint(0, 6, (2, 3))
print(a)

[[4 0 4]
 [2 4 3]]


In [40]:
a.reshape(3,2)

array([[4, 0],
       [4, 2],
       [4, 3]], dtype=int32)