Get NumPy Version & Build Info

In [2]:
import numpy as np
print(np.__version__)
print(np.show_config())

2.3.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5t0hy_xh/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5t0hy_xh/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5t0hy_xh/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5t0hy_xh/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuratio

Help for NumPy Add Function

In [3]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

TEst none are zero


In [6]:
x=np.array([1,2,3,4])
print(x)
np.all(x)

[1 2 3 4]


np.True_

In [10]:
x=np.array([1,2,3,4,0])
print(x)
np.all(x)

[1 2 3 4 0]


np.False_

Checking if there any non-zero in array

In [11]:
y=np.array([0,0,0,0,1])
print(y)
np.any(y)

[0 0 0 0 1]


np.True_

In [12]:
y=np.array([0,0,0,0,0])
print(y)
np.any(y)

[0 0 0 0 0]


np.False_

NumPy: Test a given array element-wise for finiteness (not infinity or not a Number)

In [14]:
a=np.array([1,0,np.nan,np.inf])
print(a)
print(np.isinf(a))

[ 1.  0. nan inf]
[False False False  True]


In [15]:
a=np.array([1,0,np.nan,np.inf])
print(a)
print(np.isfinite(a))

[ 1.  0. nan inf]
[ True  True False False]


Multiply two array of same size

In [22]:
x=np.array([1,2,3,4])
y=np.array([1,5,3,4])
print(np.multiply(x,y))

[ 1 10  9 16]


Making column to row and vice versa


In [24]:
nums = np.array([[[1, 2, 3, 4],
               [0, 1, 3, 4],
               [90, 91, 93, 94],
               [5, 0, 3, 2],[0, 1, 3, 4],]])
numy=nums[::-1,::-1]
print(nums)
print(numy)

[[[ 1  2  3  4]
  [ 0  1  3  4]
  [90 91 93 94]
  [ 5  0  3  2]
  [ 0  1  3  4]]]
[[[ 0  1  3  4]
  [ 5  0  3  2]
  [90 91 93 94]
  [ 0  1  3  4]
  [ 1  2  3  4]]]


Using flip


In [25]:
np.flip(nums,axis=0)

array([[[ 1,  2,  3,  4],
        [ 0,  1,  3,  4],
        [90, 91, 93, 94],
        [ 5,  0,  3,  2],
        [ 0,  1,  3,  4]]])

In [26]:
np.flip(nums,axis=1)

array([[[ 0,  1,  3,  4],
        [ 5,  0,  3,  2],
        [90, 91, 93, 94],
        [ 0,  1,  3,  4],
        [ 1,  2,  3,  4]]])

In [27]:
np.flip(nums)

array([[[ 4,  3,  1,  0],
        [ 2,  3,  0,  5],
        [94, 93, 91, 90],
        [ 4,  3,  1,  0],
        [ 4,  3,  2,  1]]])

In [28]:
y=np.ones_like(nums)
print(y)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


Replacing 3 to 9 in nums array

In [29]:
z=np.where(nums==3,9,nums)
print(z)

[[[ 1  2  9  4]
  [ 0  1  9  4]
  [90 91 93 94]
  [ 5  0  9  2]
  [ 0  1  9  4]]]


replacing element where element are lesser than

In [31]:
z=np.where(nums<4,7,nums)
print(z)

[[[ 7  7  7  4]
  [ 7  7  7  4]
  [90 91 93 94]
  [ 5  7  7  7]
  [ 7  7  7  4]]]


Extracting number from numpy array

In [32]:
m=z[z>7]
print(m)

[90 91 93 94]


In [33]:
m=z[z<=7]
print(m)

[7 7 7 4 7 7 7 4 5 7 7 7 7 7 7 4]


Sorting by row

In [58]:
print(np.sort(numy))


[[[ 0  1  3  4]
  [ 0  2  3  5]
  [90 91 93 94]
  [ 0  1  3  4]
  [ 1  2  3  4]]]


In [55]:
print(np.sort(numy,axis=1))


[[[ 0  0  3  2]
  [ 0  1  3  4]
  [ 1  1  3  4]
  [ 5  2  3  4]
  [90 91 93 94]]]


In [65]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a NumPy array 'nums' with shape (5, 6) filled with zeros of integer type
nums = np.zeros(shape=(5, 6), dtype='int')

# Printing a message indicating the original array
print("Original array:")
print(nums)

# Assigning value 3 to every alternate row and column starting from index 0
nums[::3, ::2] = 3

# Assigning value 7 to every alternate row starting from index 1 and every column starting from index 0
nums[1::3, ::2] = 7

# Printing the updated array after assigning values 3 and 7
print("\nNew array:")
print(nums)


Original array:
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

New array:
[[3 0 3 0 3 0]
 [7 7 7 7 7 7]
 [0 0 0 0 0 0]
 [3 0 3 0 3 0]
 [7 7 7 7 7 7]]
